frames_dir: data/train/timesteps_{timestep}/plots
output_dir: data/train/timesteps_{timestep}/animations

animation:
  frame_pattern: sample_%04d_xz.png
  output_file_template: "{class_name}_xz.mp4"
  ignore_dirs:
    - sample_plots
    - colormaps

colormap_animation:
  frames_dir: colormaps
  frame_pattern: colormap_%04d.png
  output_file: colormaps.mp4
