file_template: /wrk-vakka/group/spacephysics/vlasiator/2D/BCH/bulk/bulk.000{timestep:04d}.vlsv

output_dirs:
  train: data/train
  test: data/test

labels:
  reconnection: 1
  lobe: 0
  other: -1

creation:
  n_jobs: 4

class_coords_re:
  reconnection:
    - [-12, 0, 0]
  lobe:
    - [-12, 0, 8]
  other:
    - [-10, 0, 0]
    - [-17, 0, 0]
