file_template: /wrk-vakka/group/spacephysics/vlasiator/2D/BCH/bulk/bulk.000{timestep:04d}.vlsv

output_dirs:
  train: data/train
  test: data/test

labels:
  reconnection: 1
  lobe: 0

reconnection_coord_re: [-12, 0, 0]
lobe_coord_re: [-12, 0, 8]