file_template: /wrk-vakka/group/spacephysics/vlasiator/2D/BCH/bulk/bulk.000{timestep:04d}.vlsv

output_dir: data/processed

labels:
  lobe: 0
  reconnection: 1

lobe_coord_re: [-12, 0, 6]
reconnection_coord_re: [-12, 0, 0]