dataset_dir: data/train/timesteps_{timestep}
output_dir: data/train/timesteps_{timestep}/plots
dataset_config: configs/create_dataset.yaml

plot:
  n_jobs: 24
  vdflim: 2000000.0
  colormap:
    boxre: [-25, -10, -9, 9]
    vmin: -1500000.0
    vmax: 1500000.0