file_template: /wrk-vakka/group/spacephysics/vlasiator/2D/BCH/bulk/bulk.000{timestep:04d}.vlsv

model_dir: data/models/multilayer_perceptron_classifier/{model_id}
output_dir: data/predictions/multilayer_perceptron_classifier/{model_id}/timesteps_{timestep}

labels:
  reconnection: 1
  lobe: 0
  other: -1

plot:
  vdflim: 2000000.0
