file_template: /wrk-vakka/group/spacephysics/vlasiator/2D/BCH/bulk/bulk.000{timestep:04d}.vlsv

model_dir: data/models/pytorch_multilayer_perceptron_classifier/{model_id}
output_dir: data/predictions/pytorch_multilayer_perceptron_classifier/{model_id}/timesteps_{timestep}

labels:
  lobe: 0
  other: 1
  o_point: 2
  reconnection: 3

plot:
  vdflim: 2000000.0
